In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.load_csv('Movimientos_Facturas.csv', sep=';', encoding='latin')

AttributeError: module 'pandas' has no attribute 'load_csv'

In [3]:
pd.read_csv('Movimientos_Facturas.csv', sep=';', encoding='latin')

,Factura_Ser_Ejer_Num,Num_Pedido,Pedido_Ser_Ejer_Num,Fecha,Importe_Factura,Cantidad,Precio,Existencia,Coste,Mi Margen,...,Fecha_Pedido,Web,Cod_Comercial,Nom_Comercial,Serie_Factura,Cod_Postal,Nom_Serie_Factura,Cod_Provincia,Cod_Cliente,Nomb_Cliente
0,09-PM/22-01433,1976,01/09-PM/22-01976,21/11/2022,"12,40",1,"12,40",144,"4,00","0,6774",...,21/11/2022,No,54985.0,Beatriz Bocos,45.0,NaN,PLATAFORMAS,NaN,66999.0,CLIENTE FACTURA SIMPLIFICADA EBAY
1,09-PM/22-01432,1975,01/09-PM/22-01975,21/11/2022,"47,94",2,"23,97",339,"17,24","0,2807",...,21/11/2022,No,54985.0,Beatriz Bocos,45.0,NaN,PLATAFORMAS,NaN,66999.0,CLIENTE FACTURA SIMPLIFICADA EBAY
2,09-PM/22-01431,1974,01/09-PM/22-01974,21/11/2022,"51,47",1,"51,47",70,"28,94","0,4377",...,21/11/2022,No,54985.0,Beatriz Bocos,45.0,NaN,PLATAFORMAS,NaN,66999.0,CLIENTE FACTURA SIMPLIFICADA EBAY
3,09-PM/22-01430,1990,01/09-PM/22-01990,21/11/2022,"15,70",1,"15,70",144,"4,00","0,7452",...,21/11/2022,No,54985.0,Beatriz Bocos,45.0,NaN,PLATAFORMAS,NaN,66998.0,CLIENTE FACTURA SIMPLIFICADA ALI EXPRESS
4,09-PM/22-01429,1991,01/09-PM/22-01991,21/11/2022,"84,30",1,"84,30",304,"47,39","0,4378",...,21/11/2022,No,54985.0,Beatriz Bocos,45.0,NaN,PLATAFORMAS,NaN,66998.0,CLIENTE FACTURA SIMPLIFICADA ALI EXPRESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167,08-I/22-00148,3421,01/08-I/22-03421,11/11/2022,"0,00",1,"0,00",0,"0,00","0,0000",...,12/9/2022,No,500.0,.Sin Comercial,2.0,NaN,Interna,NaN,65039.0,ERROR INFORMATICO
3168,08-I/22-00131,2900,01/08-I/22-02900,7/10/2022,"0,00",1,"0,00",0,"0,00","0,0000",...,31/8/2022,No,500.0,.Sin Comercial,2.0,NaN,Interna,NaN,65039.0,ERROR INFORMATICO
3169,08-I/22-00130,2895,01/08-I/22-02895,7/10/2022,"0,00",1,"0,00",0,"0,00","0,0000",...,12/8/2022,No,500.0,.Sin Comercial,2.0,NaN,Interna,NaN,65039.0,ERROR INFORMATICO
3170,08-I/22-00129,2889,01/08-I/22-02889,7/10/2022,"0,00",1,"0,00",0,"0,00","0,0000",...,29/7/2022,No,500.0,.Sin Comercial,2.0,NaN,Interna,NaN,65039.0,ERROR INFORMATICO
3171,08-I/22-00147,2336,01/08-I/22-02336,11/11/2022,"0,00",1,"0,00",0,"0,00","0,0000",...,15/7/2022,No,500.0,.Sin Comercial,2.0,NaN,Interna,NaN,65039.0,ERROR INFORMATICO

In [4]:
movimientos = pd.read_csv('Movimientos_Facturas.csv', sep=';', encoding='latin')

In [5]:
movimientos.dtypes

Factura_Ser_Ejer_Num     object
Num_Pedido               object
Pedido_Ser_Ejer_Num      object
Fecha                    object
Importe_Factura          object
Cantidad                 object
Precio                   object
Existencia                int64
Coste                    object
Mi Margen                object
Articulo_Referencia      object
Articulo_Descripcion     object
Su_pedido                object
Cod_Delegacion           object
Hora_Pedido              object
Peso_Pedido             float64
Fecha_Pedido             object
Web                      object
Cod_Comercial           float64
Nom_Comercial            object
Serie_Factura           float64
Cod_Postal               object
Nom_Serie_Factura        object
Cod_Provincia           float64
Cod_Cliente             float64
Nomb_Cliente             object
dtype: object

In [6]:
actor_name = ('Jose Luis', 'Maria', 'Carlos', 'Scarlet')
actor_age = (34, 18, 50, 42)

In [7]:
impor pandas as pd

SyntaxError: invalid syntax (2694073151.py, line 1)

In [8]:
import pandas as pd

In [9]:
pd.Series({name:age for name, age in zip(actor_name, actor_age)})

Jose Luis    34
Maria        18
Carlos       50
Scarlet      42
dtype: int64

In [10]:
actor_dict = {name:age for name, age in zip(actor_name, actor_age)}

In [11]:
actor_dict

{'Jose Luis': 34, 'Maria': 18, 'Carlos': 50, 'Scarlet': 42}